log.console = true
log.console.level = info

management.tcp.port = 15672

management.load_definitions = /etc/rabbitmq/definitions.json

vm_memory_high_watermark.relative = 0.6
disk_free_limit.absolute = 2GB

heartbeat = 60

default_user = g57
default_pass = g57123456
default_vhost = /
