apiVersion: v1
kind: ConfigMap
metadata:
  name: g57-config
  namespace: g57
data:
  redis-url: "redis://:redis123@redis:6379"
  rabbitmq-url: "amqp://g57:g57123456@rabbitmq:5672/"
  minio-endpoint: "minio:9000"
  minio-use-ssl: "false"
  minio-bucket-raw: "videos-raw"
  minio-bucket-processed: "videos-processed"
  postgres-host: "postgres"
  postgres-port: "5432"
  smtp-host: "smtp.gmail.com"
  smtp-port: "587"
  smtp-from: "noreply@g57.com"
  notification-queue: "notification.queue"
